# Generated by Django 6.0.4 on 2026-04-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_avatar_url_user_bio_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
